name: /Users/donguk/mambaforge3/envs/firsttry
channels:
  - conda-forge
  - https://conda.software.inl.gov/public
dependencies:
  - python
  - intel-fortran-rt
  - mpich
  - paraview
  - pycalphad
  - fftw
  - gfortran
